openapi: '3.0.2'
info:
  title: matchmaker
  version: '1.0'
servers:
  - url: https://baseball.themirai.net/matchmaker/v1/
paths:
  /match:
    get:
      description: "register and match"
      responses:
        '200':
          description: OK
