apiVersion: apps/v1
kind: Deployment
metadata:
  name: akemon-deployment
spec:
  selector:
    matchLabels:
      app: akemon
  template:
    metadata:
      labels:
        app: akemon
    spec:
      containers:
      - name: akemon
        image: hardplant/akemon-redis
        ports:
        - containerPort: 8080
