apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sts
spec:
  serviceName: "redis"
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.5-alpine
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 6379
    volumeClaimTemplates:
      
