openapi: '3.0.2'
info:
  title: rankboard
  version: '1.0'
servers:
  - url: https://baseball.themirai.net/rankboard/v1/
paths:
  /score:
    get:
      responses:
        '200':
          description: OK
    post:
      responses:
        '200':
          description: OK