apiVersion: v1
kind: Service
metadata:
  name: lobby-service
spec:
  type: ClusterIP
  selector:
    app: lobby
  ports:
  - name: web
    port: 8080
    targetPort: 80
  - name: web
    port: 8443
    targetPort: 443
  - name: matchmaker
    port: 8080
    targetPort: 4444